{{- if and .Values.apiServerProxy.enabled .Values.apiServerProxy.proxyClass.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: {{ .Values.apiServerProxy.proxyClass.name }}
  labels:
    app.kubernetes.io/name: glossia-tailscale-operator
    app.kubernetes.io/component: kube-apiserver-proxy
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  statefulSet:
    pod:
      nodeSelector:
        {{- toYaml .Values.apiServerProxy.proxyClass.nodeSelector | nindent 8 }}
      {{- with .Values.apiServerProxy.proxyClass.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tailscaleContainer:
        resources:
          {{- toYaml .Values.apiServerProxy.proxyClass.resources | nindent 10 }}
{{- end }}
