{{- if .Values.apiServerProxy.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: {{ .Values.apiServerProxy.name }}
  labels:
    app.kubernetes.io/name: glossia-tailscale-operator
    app.kubernetes.io/component: kube-apiserver-proxy
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  type: kube-apiserver
  replicas: {{ .Values.apiServerProxy.replicas }}
  {{- if .Values.apiServerProxy.proxyClass.enabled }}
  proxyClass: {{ .Values.apiServerProxy.proxyClass.name }}
  {{- end }}
  tags:
    {{- toYaml .Values.apiServerProxy.tags | nindent 4 }}
  kubeAPIServer:
    mode: {{ .Values.apiServerProxy.mode }}
    hostname: {{ .Values.apiServerProxy.hostname }}
{{- end }}
