defmodule Glossia.ContentSources.Platform do
  @moduledoc ~S"""
  This module defines the behaviour of a content source. A content source is a platform
  that Glossia can establish a CRUD interface with to localize content. To understand this
  interface, it's important to familiarize with the terminology used in the module.

  ## Terminology
  - **Content source** - A platform that Glossia can establish a CRUD interface with to localize content (e.g. GitHub)
  - **Content source ID** - The ID that represents a Glossia project in the content source platform (e.g. repository ID for GitHub)
  - **Content ID** - The ID that represents a piece of content in the content source platform (e.g. file path for GitHub)
  - **Version** - The version of the content. In the case of content sources like GitHub, it represents the commit SHA when pulling a specific version.
  """

  @type version_requirement_t :: :latest | {:version, String.t()}

  @doc ~S"""
  If the content source supports versioning, like GitHub through commits,
  it returns true. Otherwise, it returns false.
  """
  @callback supports_versioning?() :: boolean()

  @doc ~S"""
  It returns the versions of the project in the content source.

  ## Parameters
  - `id_in_content_platform` - The ID that represents the project in the content source platform.
  """
  @callback get_versions(id_in_content_platform :: String.t()) ::
              {:ok, [any()]} | {:error, any()}

  @doc ~S"""
  Different content sources name versions differently. For example, in the case of GitHub,
  it is "commit"
  """
  @callback version_term() :: String.t()

  @doc ~S"""
  It returns the most recent version. In the case of a Git content source, it returns
  the most recent commit sha in the default branch.

  ## Parameters
  - `id_in_content_platform` - The id that represents the project in the content source platform.

  ## Examples

      iex> Glossia.ContentSources.Platforms.GitHub.get_most_recent_version(github_content_source)
      {:ok, "6c325ef99cb6afa8d0cb87a565dc1f59ab46fb67"}
  """
  @callback get_most_recent_version(id_in_content_platform :: String.t()) ::
              {:ok, String.t()} | {:error, any()}

  @doc ~S"""
  It returns the content from a content source.

  ## Parameters
  - `id_in_content_platform` - The id that represents the project in the content source platform.
  - `content_id` - The content id. What it refers to depends on the content source. For example, in the case of a Git repository is the path to the file.
  - `version` - The version of the content.
  """
  @callback get_content(
              id_in_content_platform :: String.t(),
              content_id :: String.t(),
              version :: String.t()
            ) ::
              {:ok, String.t()} | {:error, any()}

  @type update_content_opts_t :: %{
          title: String.t(),
          description: String.t(),
          version: String.t(),
          content: [[id: String.t(), content: String.t()]]
        }

  @doc ~S"""
  It updates the content in a content source. In the case of Git, it does so by creating a new commit
  and including the changes in it.

  # Parameters
  - `id_in_content_platform` - The id that represents the project in the content source platform.
  - `opts` - The options to configure the updating of the content.

  ## Examples

    iex> Glossia.ContentSources.Platforms.GitHub.update_content(github_content_source, %{
      title: "My new title",
      description: "My new description",
      version: "6c325ef99cb6afa8d0cb87a565dc1f59ab46fb67",
      content: [
        {id: "README.md", content: "My new content"}
      ]
    })
    {:ok, "6c325ef99cb6afa8d0cb87a565dc1f59ab46fb67"}
  """
  @callback update_content(
              id_in_content_platform :: String.t(),
              opts :: update_content_opts_t()
            ) ::
              {:ok, %{id: String.t(), url: String.t() | nil}}
              | {:error, any()}
              | {:error, :newer_version_exists}

  @type get_content_branch_id_opts_t :: %{version: String.t()}

  @doc ~S"""
  Given a version of the content, it returns the branch id. For example, in the case of GitHub,
  it returns the name of the branch. This is useful to be able to run updates concurrently and
  cancel running updates when new versions are available.
  """
  @callback get_content_branch_id(
              id_in_content_platform :: String.t(),
              opts :: get_content_branch_id_opts_t
            ) ::
              String.t()

  @doc ~S"""
  It returns true if a version of the content should be localized. For example,
  in the case of a content source like GitHub, a commit generated by Glossia should
  not trigger a localization.

  # Parameters
  - `id_in_content_platform` - The id that represents the project in the content source platform.
  - `version` - The version of the content. For example, in the case of GitHub it represents the commit sha.

  # Example

      iex> Glossia.ContentSources.Platforms.GitHub.should_localize?("6c325ef99cb6afa8d0cb87a565dc1f59ab46fb67")
      false
  """
  @callback should_localize?(id_in_content_platform :: String.t(), version :: String.t()) ::
              boolean()

  @type update_status_t :: :error | :failure | :pending | :success

  @doc ~S"""
  It updates the state of a localization in the content source. For example, in the case of GitHub,
  it updates the status of a commit.

  # Parameters
  - `id_in_content_platform` - The id that represents the project in the content source platform.
  - `state` - The state of the localization.
  - `version` - The version of the content. For example, in the case of GitHub it represents the commit sha.
  - `opts` - The options to configure the updating of the state.
  """
  @callback update_state(
              id_in_content_platform :: String.t(),
              state :: update_status_t(),
              version :: String.t(),
              opts :: [{:target_url, String.t() | nil}, {:description, String.t() | nil}]
            ) :: :ok | {:error, any()}

  @callback generate_auth_token(id_in_content_platform :: any()) ::
              {:ok, String.t()} | {:error, any()}

  @callback is_webhook_payload_valid?(
              req_headers :: Keyword.t(),
              payload :: map()
            ) :: boolean()
end
