[plugins]
elixir = "https://github.com/mise-plugins/mise-elixir"

[tools]
"elixir" = "1.16.0"
"flyctl" = "0.1.104"
"deno" = "1.39.1"
"erlang" = "26.2.1"

[tasks."marketing:dev"]
description = 'Dev the marketing website'
run = "pnpm run -C marketing dev"

[tasks."marketing:build"]
description = 'Build the marketing website'
run = "pnpm run -C marketing build"

[tasks."docs:dev"]
description = 'Dev the docs website'
run = "pnpm run -C docs dev"

[tasks."docs:build"]
description = 'Build the docs website'
run = "pnpm run -C docs build"

[tasks."handbook:dev"]
description = 'Dev the handbook website'
run = "pnpm run -C handbook dev"

[tasks."handbook:build"]
description = 'Build the handbook website'
run = "pnpm run -C handbook build"