[tools]
erlang = "latest"
elixir = "latest"
go = "1.22.0"
aws-cli = "2"
terraform = "1"
packer = "1"
hcloud = "latest"
kubectl = "latest"
helm = "3"
op = "latest"
ruby = "3.4.7"
git-cliff = "2.10.0"

[env]
_.file = ".env"
_.source = "{{config_root}}/mise/utilities/dev_instance_env.sh"
