apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: glossia
  namespace: flux-system
spec:
  image: ghcr.io/glossia/glossia
  interval: 1m0s
  secretRef:
    name: ghcr-glossia
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: glossia
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: glossia
  filterTags:
    pattern: "^main$"
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: glossia
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(deploy): update production image"
    push:
      branch: main
  update:
    path: ./infra/k8s/workload-apps/glossia-production
    strategy: Setters
