apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-app-reconciler
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-app-reconciler
  namespace: org-glossia
rules:
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-app-reconciler
  namespace: org-glossia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-app-reconciler
subjects:
  - kind: ServiceAccount
    name: workload-app-reconciler
    namespace: flux-system
