name: Deploy
on:
  push:
    branches:
      - main

env:
  MISE_EXPERIMENTAL: "1"
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  production:
    name: Production
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/jdx/mise-action@v2
        with:
          cache: true
      - run: flyctl deploy --remote-only
