name: Release
on:
  push:
    branches:
      - main

env:
  MISE_EXPERIMENTAL: "1"
  MISE_GITHUB_TOKEN: ${{ secrets.GLOSSIA_GITHUB_TOKEN }}
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  glossia:
    name: Glossia
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - run: curl https://mise.run | sh
      - run: ~/.local/bin/mise install
      - run: ~/.local/bin/mise run release
