name: Release
on:
  push:
    branches:
      - main

env:
  MISE_EXPERIMENTAL: "1"
  MISE_GITHUB_TOKEN: ${{ secrets.GLOSSIA_GITHUB_TOKEN }}
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  glossia:
    name: Glossia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/docker/setup-docker-action@v4
      - uses: https://github.com/jdx/mise-action@v2
        with:
          cache: true
      - run: mise run release