apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: babel
  namespace: org-glossia
spec:
  dependsOn:
    - name: platform
  maxHistory: 5
  interval: 10m0s
  releaseName: babel
  targetNamespace: babel
  storageNamespace: babel
  kubeConfig:
    secretRef:
      name: glossia-production-kubeconfig
  chart:
    spec:
      chart: ./deploy/helm/babel
      interval: 5m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - deploy/helm/babel/values.yaml
        - ops/deploy/values-babel-production.yaml
  install:
    createNamespace: true
    crds: Create
    strategy:
      name: RetryOnFailure
      retryInterval: 2m0s
  upgrade:
    cleanupOnFail: false
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 2m0s
  timeout: 20m0s
  values:
    image:
      repository: ghcr.io/glossia/glossia-babel # {"$imagepolicy": "flux-system:babel:name"}
      tag: main-8-43e3678831fb268cc91250fd94aac2bed3b6b91f # {"$imagepolicy": "flux-system:babel:tag"}
      digest: "" # {"$imagepolicy": "flux-system:babel:digest"}
