apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 24h
  releaseName: reloader
  targetNamespace: reloader
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    cleanupOnFail: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: reloader
      version: 2.2.12
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    reloader:
      reloadStrategy: annotations
      deployment:
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 512Mi
