{{- if .Values.pomeriumAccessIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "glossia.fullname" . }}-pomerium-access
  labels:
    {{- include "glossia.labels" . | nindent 4 }}
    app.kubernetes.io/component: pomerium-access
  {{- with .Values.pomeriumAccessIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.pomeriumAccessIngress.className }}
  rules:
    {{- range .Values.pomeriumAccessIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "glossia.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- with .Values.pomeriumAccessIngress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
