import Config

# Configure your database
config :glossia, Glossia.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "glossia_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :glossia, Glossia.ClickHouseRepo,
  hostname: "localhost",
  port: 8123,
  database: "glossia_dev",
  settings: [readonly: 1]

config :glossia, Glossia.IngestRepo,
  hostname: "localhost",
  port: 8123,
  database: "glossia_dev",
  flush_interval_ms: 5000,
  max_buffer_size: 100_000,
  pool_size: 5

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :glossia, GlossiaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4050],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "65pP1xr3jmj+N1BsGXNwwYPPpS7aG7F6dj38YdnvijVD204/u7fKbSWRZ9rY6Jv0",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:glossia, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :glossia, GlossiaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r/priv\/static\/(?!uploads\/).*\.(js|css|png|jpeg|jpg|gif|svg)$/,
      # Gettext translations
      ~r/priv\/gettext\/.*\.po$/,
      # Router, Controllers, LiveViews and LiveComponents
      ~r/lib\/glossia_web\/router\.ex$/,
      ~r/lib\/glossia_web\/(controllers|live|components)\/.*\.(ex|heex)$/
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :glossia, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# OAuth providers are configured at runtime via config/runtime.exs
# which reads GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, GITLAB_CLIENT_ID,
# and GITLAB_CLIENT_SECRET from environment variables (e.g. via fnox).

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Keep local Chrome usable while running `mix phx.server`.
# ChromicPDF runs a persistent headless Google Chrome process.
config :glossia, Glossia.OgImage, enabled: false

# Cloak encryption vault (deterministic dev key)
config :glossia, Glossia.Vault,
  ciphers: [
    default: {
      Cloak.Ciphers.AES.GCM,
      tag: "AES.GCM.V1",
      key: Base.decode64!("L1gSQ6tifJPmcSH/5s3apb+SApxmeIkwXk/j2sjXbxE="),
      iv_length: 12
    }
  ]
