apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../workloads/production
patches:
  - target:
      group: cluster.x-k8s.io
      version: v1beta2
      kind: Cluster
      name: glossia-production
    path: cluster-topology.yaml
