{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgres.appSecretName }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.postgres.appSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: {{ .Values.postgres.user | quote }}
        password: {{ printf "{{ .%s }}" .Values.externalSecrets.databasePasswordField | quote }}
        redis-password: {{ printf "{{ .%s }}" .Values.externalSecrets.redisPasswordField | quote }}
        smtp-username: {{ printf "{{ .%s }}" .Values.externalSecrets.mailRelayUsernameField | quote }}
        smtp-password: {{ printf "{{ .%s }}" .Values.externalSecrets.mailRelayPasswordField | quote }}
  data:
    - secretKey: {{ .Values.externalSecrets.databasePasswordField }}
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemKey .Values.externalSecrets.databasePasswordField | quote }}
    - secretKey: {{ .Values.externalSecrets.redisPasswordField }}
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemKey .Values.externalSecrets.redisPasswordField | quote }}
    - secretKey: {{ .Values.externalSecrets.mailRelayUsernameField }}
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemKey .Values.externalSecrets.mailRelayUsernameField | quote }}
    - secretKey: {{ .Values.externalSecrets.mailRelayPasswordField }}
      remoteRef:
        key: {{ printf "%s/%s" .Values.externalSecrets.itemKey .Values.externalSecrets.mailRelayPasswordField | quote }}
{{- end }}
