# Production workload cluster overlay.

tailscale-operator:
  operatorConfig:
    hostname: glossia-k8s-production
    defaultTags:
      - "tag:glossia-k8s-production"
  proxyConfig:
    defaultTags: "tag:glossia-k8s-production"

apiServerProxy:
  name: glossia-production-kube
  hostname: glossia-production-kube
  tags:
    - "tag:glossia-k8s-production"
  proxyClass:
    name: glossia-production-kube
