apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glossia
  namespace: org-glossia
spec:
  dependsOn:
    - name: platform
  maxHistory: 5
  interval: 10m0s
  releaseName: glossia
  targetNamespace: glossia
  storageNamespace: glossia
  kubeConfig:
    secretRef:
      name: glossia-production-kubeconfig
  chart:
    spec:
      chart: ./deploy/helm/glossia
      interval: 5m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - deploy/helm/glossia/values.yaml
        - deploy/values-production.yaml
        - deploy/values-object-storage-hetzner.yaml
  install:
    createNamespace: true
    crds: Create
    strategy:
      name: RetryOnFailure
      retryInterval: 2m0s
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 2m0s
  timeout: 20m0s
  values:
    image:
      repository: ghcr.io/glossia/glossia # {"$imagepolicy": "flux-system:glossia:name"}
      tag: main # {"$imagepolicy": "flux-system:glossia:tag"}
      digest: sha256:2a092d2ff9fb754d55bb7c0745ec7b5aee159a756fedec79a5fac81e7a0a0d05 # {"$imagepolicy": "flux-system:glossia:digest"}
