{{- if .Values.http01ClusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.http01ClusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email | quote }}
    server: {{ .Values.http01ClusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.http01ClusterIssuer.name }}-account
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.http01ClusterIssuer.ingressClassName | quote }}
{{- end }}
