{{- if and .Values.rookObjectStorage.enabled .Values.rookObjectStorage.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-rgw-ingress" .Values.rookObjectStorage.objectStoreName }}
  namespace: {{ .Values.rookObjectStorage.clusterNamespace }}
  labels:
    app.kubernetes.io/name: glossia-platform
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: rook-ceph-rgw
      rook_cluster: {{ .Values.rookObjectStorage.clusterNamespace }}
      rook_object_store: {{ .Values.rookObjectStorage.objectStoreName }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.rookObjectStorage.clusterNamespace }}
      ports:
        - protocol: TCP
          port: 80
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.rookObjectStorage.appNamespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.rookObjectStorage.networkPolicy.appPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: 80
{{- end }}
