apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pomerium-ingress-controller
  namespace: org-glossia
spec:
  interval: 1h
  ref:
    branch: 0-33-0
  url: https://github.com/pomerium/ingress-controller.git
