apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pomerium-configuration
  namespace: org-glossia
spec:
  dependsOn:
    - name: pomerium-controller
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: authenticate-glossia-ai
      namespace: pomerium
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: pomerium-google-identity-provider
      namespace: pomerium
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: pomerium-postgres
      namespace: pomerium
  interval: 10m0s
  path: ./ops/infra/k8s/workload-platforms/glossia-production/pomerium
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 20m0s
  kubeConfig:
    secretRef:
      name: glossia-production-kubeconfig
