apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pomerium-controller
  namespace: org-glossia
spec:
  interval: 10m0s
  path: ./config/default
  patches:
    - patch: |
        - op: add
          path: /metadata/annotations
          value:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            external-dns.alpha.kubernetes.io/hostname: authenticate.glossia.ai
            load-balancer.hetzner.cloud/location: fsn1
            load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
      target:
        kind: Service
        name: pomerium-proxy
    - patch: |
        - op: replace
          path: /spec/replicas
          value: 2
        - op: add
          path: /spec/template/spec/affinity
          value:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: pomerium
                        app.kubernetes.io/component: proxy
                    topologyKey: kubernetes.io/hostname
        - op: add
          path: /spec/template/spec/tolerations
          value:
            - key: node.cluster.x-k8s.io/pool
              operator: Equal
              value: stateful
              effect: NoSchedule
      target:
        group: apps
        version: v1
        kind: Deployment
        name: pomerium
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: pomerium/ingress-controller:v0.33.1
        - op: replace
          path: /spec/template/spec/containers/0/imagePullPolicy
          value: IfNotPresent
      target:
        group: batch
        version: v1
        kind: Job
        name: pomerium-gen-secrets
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: pomerium-ingress-controller
  timeout: 15m0s
  kubeConfig:
    secretRef:
      name: glossia-production-kubeconfig
