apiVersion: v1
kind: Namespace
metadata:
  name: glossia
  labels:
    app.kubernetes.io/part-of: glossia
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: glossia
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/part-of: glossia
