apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-google-identity-provider
  namespace: pomerium
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: idp-google
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .POMERIUM_GOOGLE_CLIENT_ID }}"
        client_secret: "{{ .POMERIUM_GOOGLE_CLIENT_SECRET }}"
  data:
    - secretKey: POMERIUM_GOOGLE_CLIENT_ID
      remoteRef:
        key: /kubernetes/POMERIUM_GOOGLE_CLIENT_ID
    - secretKey: POMERIUM_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: /kubernetes/POMERIUM_GOOGLE_CLIENT_SECRET
