apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authenticate-certificate.yaml
  - google-identity-provider-external-secret.yaml
  - pomerium-global.yaml
  - postgres-app-external-secret.yaml
  - postgres-cluster.yaml
  - postgres-connection-external-secret.yaml
  - proxy-pod-disruption-budget.yaml
