apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pomerium-postgres
  namespace: pomerium
spec:
  instances: 2
  bootstrap:
    initdb:
      database: pomerium
      owner: pomerium
      secret:
        name: pomerium-postgres-app
  storage:
    size: 10Gi
    storageClass: hcloud-volumes
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    nodeSelector:
      node.cluster.x-k8s.io/pool: stateful
    tolerations:
      - key: node.cluster.x-k8s.io/pool
        operator: Equal
        value: stateful
        effect: NoSchedule
