apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-postgres-connection
  namespace: pomerium
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pomerium-postgres-connection
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: "postgresql://pomerium:{{ .POMERIUM_POSTGRES_PASSWORD | urlquery }}@pomerium-postgres-rw.pomerium.svc.cluster.local:5432/pomerium?sslmode=verify-full&target_session_attrs=read-write"
  data:
    - secretKey: POMERIUM_POSTGRES_PASSWORD
      remoteRef:
        key: /kubernetes/POMERIUM_POSTGRES_PASSWORD
