apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-postgres-app
  namespace: pomerium
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pomerium-postgres-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: pomerium
        password: "{{ .POMERIUM_POSTGRES_PASSWORD }}"
  data:
    - secretKey: POMERIUM_POSTGRES_PASSWORD
      remoteRef:
        key: /kubernetes/POMERIUM_POSTGRES_PASSWORD
