apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pomerium
  namespace: pomerium
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pomerium
      app.kubernetes.io/component: proxy
