ExUnit.start(exclude: [:live])
Ecto.Adapters.SQL.Sandbox.mode(Glossia.Repo, :manual)

Mimic.copy(ExAws)
Mimic.copy(Glossia.Mailer)
Mimic.copy(Glossia.Extensions)
Mimic.copy(Glossia.TestEventHandler)
Mimic.copy(Glossia.Github.App)
Mimic.copy(Glossia.Github.Client)
Mimic.copy(Glossia.Translations)
Mimic.copy(Glossia.Translations.RepositoryRun)
Mimic.copy(Glossia.Translations.Agent)
Mimic.copy(Condukt)
Mimic.copy(ReqLLM)
Mimic.copy(ReqLLM.Response)
