name: Builder

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: builder-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DENO_VERSION: "1.35.0"

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
            deno-version: ${{ env.DENO_VERSION }}
      - name: Test
        working-directory: priv/static/builder
        run: deno test
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
            deno-version: ${{ env.DENO_VERSION }}
      - name: Lint
        working-directory: priv/static/builder
        run: deno lint
  format:
    name: Format
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
            deno-version: ${{ env.DENO_VERSION }}
      - name: Format
        working-directory: priv/static/builder
        run: deno fmt --check