name: Glossia

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: glossia-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  OTP_VERSION: 25.0.4
  ELIXIR_VERSION: 1.14.1
  MIX_ENV: test
  GLOSSIA_PLAN: cloud
  OBAN_WEB_FETCH_PUBLIC_KEY: ${{ secrets.OBAN_WEB_FETCH_PUBLIC_KEY }}
  OBAN_WEB_AUTH_KEY: ${{ secrets.OBAN_WEB_AUTH_KEY}}

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    services:
      db:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - name: Add Oban Web repository
        run: mix hex.repo add oban https://getoban.pro/repo --fetch-public-key $OBAN_WEB_FETCH_PUBLIC_KEY --auth-key $OBAN_WEB_AUTH_KEY;

      - run: mix deps.get

      - run: mix test
  credo:
    name: Credo
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - name: Add Oban Web repository
        run: mix hex.repo add oban https://getoban.pro/repo --fetch-public-key $OBAN_WEB_FETCH_PUBLIC_KEY --auth-key $OBAN_WEB_AUTH_KEY;

      - run: mix deps.get

      - run: mix credo
  release_dry_run:
    name: Release dry run
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: docker build . -t glossia --build-arg OBAN_WEB_FETCH_PUBLIC_KEY=${{env.OBAN_WEB_FETCH_PUBLIC_KEY}} --build-arg OBAN_WEB_AUTH_KEY=${{env.OBAN_WEB_AUTH_KEY}}